# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Reciplease' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.0.0-beta.2'
# Pods for yourProjectName
target 'RecipleaseTests' do
    inherit! :search_paths
    # Pods for testing
  end
end